# .github/workflows/publish.yml
name: Publish Libphonenumber Platform interface to pub.dev

on:
  push:
    tags:
    - 'libphonenumber_platform_interface-v[0-9]+.[0-9]+.[0-9]+*'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Install Flutter"
      run: |
        cd $HOME
        git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
        echo "$HOME/_flutter/bin" >> $GITHUB_PATH
        cd $GITHUB_WORKSPACE
    - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
      with:
        working-directory: libphonenumber_platform_interface/
